// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtwaiSZa1TCnFO0lV7HN4SHWtXsH5wiBc',
    appId: '1:903604484748:web:0740576ea231bd84ccd9a9',
    messagingSenderId: '903604484748',
    projectId: 'capstone-1b6ae',
    authDomain: 'capstone-1b6ae.firebaseapp.com',
    storageBucket: 'capstone-1b6ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOHzPWZ_e0ATENZ7bI18IwVU04RZoHKF4',
    appId: '1:903604484748:android:2fe3d68b45b8b933ccd9a9',
    messagingSenderId: '903604484748',
    projectId: 'capstone-1b6ae',
    storageBucket: 'capstone-1b6ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXAXDySCaxaFMF1Yn_mI2rcpeRm8egWQ',
    appId: '1:903604484748:ios:5f13f2123af4e8deccd9a9',
    messagingSenderId: '903604484748',
    projectId: 'capstone-1b6ae',
    storageBucket: 'capstone-1b6ae.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXAXDySCaxaFMF1Yn_mI2rcpeRm8egWQ',
    appId: '1:903604484748:ios:5f13f2123af4e8deccd9a9',
    messagingSenderId: '903604484748',
    projectId: 'capstone-1b6ae',
    storageBucket: 'capstone-1b6ae.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtwaiSZa1TCnFO0lV7HN4SHWtXsH5wiBc',
    appId: '1:903604484748:web:99f96ce325824653ccd9a9',
    messagingSenderId: '903604484748',
    projectId: 'capstone-1b6ae',
    authDomain: 'capstone-1b6ae.firebaseapp.com',
    storageBucket: 'capstone-1b6ae.appspot.com',
  );
}
